### ISSUE TITLE
Implement 'Show More/All' solution for filters

### ISSUE THREAD

**Issue by jrmerz** [UCDavisLibrary/wine-search#12]
We are just going to show 10 filter options at first, then expand to show more

**Comment by jrmerz** [comment]
@wrenaria Do we have final designs for how this is going to look?  I know you were investigating a couple different possibilities.

**Comment by wrenaria** [comment]
I have two options: scroll within a section or expand section in a pop out (similar to how NYPL does it). Both are fine options and I don't think one is worse than the other, so if one is easier to implement or you have a preference, lets go with that. Or we can run it by some other people for opinions, whatever! I updated the illustrator files to show both options.

Mobile examples: https://drive.google.com/open?id=0B4y2_Xs4SL2-bzZVcEdrZXhCU1U

Desktop examples: https://drive.google.com/open?id=0B4y2_Xs4SL2-b1U0RVlyd1I5M28 

Open to thoughts/questions/ideas.

**Comment by jrmerz** [comment]
Well scrolling solution will be much easier, but if the list gets long, the pop out solution would be probably be better.  Just a lot more work.  Perhaps we pull in others? @qjhart

**Comment by qjhart** [comment]
My immediate inclination is to stay with the scrolling option.  where I see that as a problem is with the search.  I honestly don't think that will shows itself in the wine app as much as later in when we have longer lists of subject categories, so I'm thinking let's not solve a problem we aren't sure we have yet.

**Comment by jrmerz** [comment]
Simple scrolling solution implement.  Reopen if we decide we want something more.
