### ISSUE TITLE
Create wine mark icons

### ISSUE THREAD

**Issue by jrmerz** [UCDavisLibrary/wine-search#7]
Icons for wine color and type.  Will be added to cork-icon set

**Comment by jrmerz** [comment]
@wrenaria is going to generate the svgs, then @jrmerz is going to add them to the cork-icons set

**Comment by wrenaria** [comment]
SVG icons are here: https://drive.google.com/drive/folders/0B4y2_Xs4SL2-X0JYWnJ5SmNIT2c?usp=sharing

**Comment by jrmerz** [comment]
@wrenaria if you want the icons to have the border when selected, when have to duplicate these icons adding the border via SVG.  Let me know your thoughts.  The current demo is up with just the check mark and bold/colored text when selected.

**Comment by wrenaria** [comment]
The bordered icons have been added to the same folder linked in my previous comment.

**Comment by jrmerz** [comment]
Icons added.
